spring:
  application:
    name: irctc-api-gateway
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:${CONFIG_SERVICE_PORT:8888}
  profiles:
    active: dev

management:
  tracing:
    sampling:
      probability: 1.0